### ISSUE TITLE
Integrate Ko-Fi or Patreon links into user profiles

### ISSUE THREAD

**Issue by adamcoolcat** [momentum-mod/website#730] opened 2023-04-05 18:48 UTC
Ko-fi and Patreon allow users to be paid via a link. This feature will allow mappers to be directly supported for the work they perform making maps, by adding these links to the maps download page. That way, users that browse maps can support them through the Momentum Mod site itself.

Steps to complete:

1. Create an option on a user's profile page that allows them to link their patreon or ko-fi link. This link should now be saved and be editable by the user, to direct to the payment source they choose.

2. On the `dashboard/maps/xxx` page, on the author's tab, add a section that contains the patreon/kofi link. This section can be titled something like "If you would like to support this author, follow this link." The link will then direct them to the link that user placed on their profile page.

[Similar Issue](https://github.com/momentum-mod/website/issues/197)

**Comment by tsa96** [comment] 2023-04-05 19:21
Gonna close since dupe of #197. Thanks for bringing this up again though!

**Closed by tsa96** 2023-04-05 19:21 UTC
